version: "3"
services:
  postgres:
    env_file:
      - .env
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/volumes/postgres/data:/var/lib/postgresql/data

  processing:
    build:
      context: .docker/php7
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/app
      - ~/.composer:/root/.composer